# Config file for automatic testing at travis-ci.org
language: python

python:
  - 3.4
  - 3.3
  - 2.7
  - 2.6

env:
  matrix:
  - DJANGO='django>=1.5,<1.6'
  - DJANGO='django>=1.6,<1.7'

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install $DJANGO
  - pip install -r requirements-test.txt  --use-mirrors

# command to run tests using coverage, e.g. python setup.py test
script: coverage run --source djangocms_usersettings2 runtests.py

# report coverage to coveralls.io
after_success: coveralls
